spring:
  application:
    name: mp-server
  web:
    resources:
      static-locations: file:/Users/panchaohui/Desktop/mp-server/static/
  cache:
    jcache:
      config: classpath:ehcache.xml
server:
  undertow:
    buffer-size: 64
  port: 80
  servlet:
    context-path: /
wx:
  mp:
    configs:
      - appid: wx8c967dded27ba5e2
        secret: eb38c40ae87e33b06f02e42ad460d6ca
        token:
        aesKey:
        msgDataFormat:
com:
  lead:
    fund:
      base:
        url-prefix: http://localhost
        database:
          dmmp:
            url: jdbc:mysql://localhost:3306/dmmp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
            username: root
            password: password
            driver-class-name: com.mysql.cj.jdbc.Driver
          douson:
            url: jdbc:mysql://localhost:3306/douson?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
            username: root
            password: password
            driver-class-name: com.mysql.cj.jdbc.Driver