ALTER TABLE `MP_INVENTORY`
    ADD COLUMN `PLAN_QUANTITY`        DECIMAL(16, 2) COMMENT '计划数量',
    ADD COLUMN `REMAINING_QUANTITY`   DECIMAL(16, 2) COMMENT '剩余数量',
    ADD COLUMN `OUT_OF_PLAN_ORDER_NO` VARCHAR(64) COMMENT '计划外单号';