UPDATE douson.MP_FORUM SET CATEGORY = 'dousonVoiceCommunity' WHERE CATEGORY IS NULL;
UPDATE douson.MP_FORUM SET COMMENTARY_SHOW_TYPE = 0 WHERE COMMENTARY_SHOW_TYPE IS NULL;
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('nationality', '1', 'Vietnam', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('nationality', '2', 'China', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('userProperty', '3', '外部人员 cá nhân ngoài công ty', 3);
