DROP TABLE MP_DRESS;
CREATE TABLE DOUSON.MP_DRESS
(
    WORK_DRESS_TYPE        VARCHAR(64) COMMENT '工装类型',
    MATERIAL_NO            VARCHAR(64) COMMENT '物料号',
    REMARK                 VARCHAR(512) COMMENT '描述',
    DESIGN_NUMBER          VARCHAR(128) COMMENT '图号',
    APPLY_COUNT            DECIMAL(19, 2) COMMENT '申请数量',
    APPLY_DATE             VARCHAR(32) COMMENT '申请日期',
    STORE_POSITION         VARCHAR(128) COMMENT '库存位置',
    CHECK_ACCEPT_USER      VARCHAR(128) COMMENT '验收',
    DESCRIPTION_OF_ORDER   VARCHAR(512) COMMENT '备注（注明为哪个订单服务）',
    STORE_COUNT            DECIMAL(19, 2) COMMENT '入库数量',
    STORE_DATE_DESCRIPTION VARCHAR(512) COMMENT '入库日期备注',
    CREATOR                VARCHAR(64)   NULL COMMENT '创建人用户ID',
    MODIFIER               VARCHAR(64)   NULL COMMENT '修改人用户ID',
    STATE                  INT DEFAULT 0 NULL COMMENT '状态，0-正常 1-删除',
    CREATE_TIME            DATETIME      NULL COMMENT '创建时间',
    MODIFY_TIME            DATETIME      NULL COMMENT '修改时间',
    ID                     VARCHAR(64)   NOT NULL COMMENT '唯一标志',
    PRIMARY KEY (ID)
) COMMENT = '工装管理';

DROP TABLE DOUSON.MP_DRESS_ATTACHMENT;
CREATE TABLE DOUSON.MP_DRESS_ATTACHMENT
(
    DRESS_ID            VARCHAR(64)  NULL COMMENT '工装管理ID',
    ATTACHMENT_CATEGORY VARCHAR(64)  NULL COMMENT '附件分类',
    ATTACHMENT_TYPE     VARCHAR(32)  NULL COMMENT '附件类型',
    URL                 VARCHAR(256) NULL COMMENT '链接',
    FILE_ID             VARCHAR(256) NULL COMMENT '文件ID',
    FILENAME            VARCHAR(256) NULL COMMENT '文件名',
    COMPRESS_URL        VARCHAR(256) NULL COMMENT '压缩链接',
    CREATOR                VARCHAR(64)   NULL COMMENT '创建人用户ID',
    MODIFIER               VARCHAR(64)   NULL COMMENT '修改人用户ID',
    STATE                  INT DEFAULT 0 NULL COMMENT '状态，0-正常 1-删除',
    CREATE_TIME            DATETIME      NULL COMMENT '创建时间',
    MODIFY_TIME            DATETIME      NULL COMMENT '修改时间',
    ID                  VARCHAR(64)  NOT NULL COMMENT '唯一标志'
        PRIMARY KEY,
    CONSTRAINT UNQ_15110_IMPROVEATTACHMENT_0
        UNIQUE (DRESS_ID, ATTACHMENT_CATEGORY, ATTACHMENT_TYPE, URL, FILE_ID)
)
    COMMENT '工装管理附件';