INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('accidentType', '0', 'EHS安全 An toàn EHS', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('accidentType', '2', '产品质量 Chất lượng sản phẩm', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('accidentType', '4', '刀具损坏 Dao hỏng', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '1', '操作不良Thao tác không tốt', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '10', '超负荷Quá tải', 10);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '11', '制造不良Sản xuất kém', 11);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '12', '环境不良Môi trường không tốt', 12);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '13', '设计不良Thiết kế không tốt', 13);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '14', '其它（备注原因）Khác (ghi chú nguyên nhân)', 14);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '2', '设备零件不良Bộ phận thiết bị không tốt', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '3', '日常保养不良Bảo trì hàng ngày kém', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '4', '设备电气不良Điện của thiết bị không tốt', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '5', '修理不良Sửa chữa không tốt', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '6', '润滑不良Bôi trơn kém', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '7', '绝缘老化Lão hóa cách nhiệt', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '8', '精度不良Độ chính xác kém', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('brokenReason', '9', '年度维护不良Bảo trì hàng năm kém', 9);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('calibrationPeriod', '1095', '1095天', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('calibrationPeriod', '182', '182天', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('calibrationPeriod', '365', '365天', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('calibrationPeriod', '90', '90天', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('checkPoint', '1', 'Self-inspection 自检', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('checkPoint', '2', 'QC-inspection 检验员', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '1', '塞规Ren trong', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '10', '便携式硬度计Thiết bị đo độ cứng cầm tay', 10);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '11', '表面粗糙度比较块Khối so sánh độ nhám bề mặt', 11);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '12', '测长仪 Dụng cụ đo chiều dài', 12);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '13', '齿顶高度规Thiết bị đo chiều cao đầu tip', 13);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '14', '齿厚测量规 Thiết bị đo độ dày răng', 14);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '15', '磁轭式磁粉探伤机Thiết bị dò Yoke', 15);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '16', '磁粉探伤机Thiết bị dò từ tính', 16);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '17', '粗糙度仪Thiết bị đo độ nhám', 17);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '18', '大理石平台Bàn đá cẩm thạch', 18);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '19', '读数显微镜Thiết bị đọc hiển vi', 19);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '2', '带表卡尺 Thước cặp có đồng hồ', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '20', '防震精密压力表 Đồng hồ đo áp suất chính xác chống sốc', 20);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '21', '杠杆百分表Đồng hồ đo kiểm tra quay số', 21);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '22', '高精度英制表Đồng hồ đo độ chính xác', 22);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '23', '高斯计Gauss Meter', 23);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '24', '关节式三坐标 CMM', 24);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '25', '管状内径千分尺Thiết bị đo ống bên trong', 25);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '26', '红外测温仪Nhiệt kế hồng ngoại', 26);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '27', '环规Ren ngoài', 27);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '28', '精密压力表Thiết bị đo áp suất chính xác', 28);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '29', '卡尺专用量块套装Bộ khối đo kiểm tra thước cặp', 29);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '3', '带表卡尺(英制) Thước cặp có đồng hồ(inch)', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '30', '梨型滴定管Burette quả lê', 30);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '31', '链条式硬度计Máy đo độ cứng King Brinell', 31);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '32', '螺距标准块Khối tiêu chuẩn cao độ', 32);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '33', '螺距测量规Thiết bị đo bước ren', 33);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '34', '内径百分表Đồng hồ đo bên trong', 34);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '35', '内径量表Bộ đo lỗ khoan', 35);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '36', '内径量表(英制) Thiết bị đo đường kính lỗ khoan (inch)', 36);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '37', '内径千分尺Thiết bị đo đường kính trong', 37);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '38', '内径千分尺组件Thiết bị đo ống bên trong', 38);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '39', '内螺纹中径检测规Đồng hồ đo đường kính trung bình cho ren trong', 39);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '4', '61°规 61°GAGE', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '40', '内螺纹锥度测量规Thước đo độ côn ren trong', 40);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '41', '牛顿砝码(提升力试块) Khối thử lực nâng', 41);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '42', '球形规Thiết bị đo hình cầu', 42);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '43', '塞规Ren trong', 43);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '44', '三爪内径千分尺Thiết bị đo đường kính 3 chân', 44);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '45', '深度尺Thiết bị đo độ sâu', 45);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '46', '深度规Thiết bị đo độ sâu', 46);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '47', '湿温度表Chỉ báo nhiệt độ và độ ẩm', 47);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '48', '数显布氏硬度计Thiết bị đo độ cứng Brinell kỹ thuật số', 48);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '49', '数显单钩深度尺Đồng hồ đo độ sâu Hook kỹ thuật số', 49);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '5', 'R半径规Máy đo bán kính R', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '50', '数显高度尺Thước đo chiều cao kỹ thuật số', 50);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '51', '数显卡尺Thước cặp kĩ thuật số ', 51);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '52', '数显内沟槽卡尺Thước kẹp rãnh bên trong kỹ thuật số', 52);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '53', '数显内径表Thiết bị đo đường kính bên trong kỹ thuật số', 53);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '54', '数显内径千分表Đồng hồ đo kỹ thuật số bên trong', 54);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '55', '数显内卡规Thước cặp đo lường kỹ thuật số bên trong', 55);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '56', '数显扭矩扳手Cờ lê lực kỹ thuật số', 56);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '57', '数显千分表Đồng hồ đo kỹ thuật số', 57);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '58', '数显千分尺Chỉ báo kỹ thuật số cho đồng hồ đo lỗ', 58);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '59', '数显三爪内径千分尺 Bộ micrômet điện tử ba điểm bên trong (có vòng cài đặt)', 59);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '6', 'V型槽槽宽检测规Thiết bị đo chiều rộng rãnh chữ V', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '60', '数显外径千分尺(英制) Micrômet ngoài điện tử', 60);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '61', '数显深度百分表Thiết bị đo độ sâu kĩ thuật số', 61);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '62', '数字式木材测湿仪Máy kiểm tra độ ẩm gỗ kỹ thuật số', 62);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '63', '双钩数显深度尺Máy đo độ sâu móc đôi kỹ thuật số', 63);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '64', '台式洛氏硬度计Máy đo độ cứng Rockwell', 64);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '65', '通径规Thiết bị đo đường kính', 65);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '66', '投影仪máy chiếu', 66);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '67', '涂层测量仪Thiết bị đo độ dày lớp phủ', 67);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '68', '外径千分尺Thiết bị đo đường kính ngoài', 68);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '69', '外螺纹中径检测规Thiết bị đo đường kính trung bình cho ren ngoài', 69);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '7', 'V型槽检测规Thiết bị đo kiểm tra rãnh chữ V', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '70', '万能角度尺Thước đo góc vạn năng', 70);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '71', '橡胶硬度计máy đo độ cứng cao su LX-A', 71);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '72', '压力变送器Thiết bị phát áp suất', 72);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '73', '牙高标准规Tiêu chuẩn chiều cao ren', 73);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '74', '牙型样板规 Máy đo mẫu loại răng', 74);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '75', '英制百分表Đồng hồ đo mặt số Imperial', 75);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '76', '英制量块组件Bộ khối đo', 76);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '77', '游标卡尺 Thước cặp Vernier', 77);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '78', '预置式扭力扳手Cờ lê lực cài đặt sẵn', 78);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '79', '长爪内测游标卡尺Long claw internal test vernier caliper', 79);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '8', '白光照度计Thiết bị đo ánh sáng trắng', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '80', '锥螺纹中经测量规Thiết bị đo đường kính bước ren côn', 80);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '81', '锥尾测量规 Thước đo đuôi côn', 81);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '82', '紫外辐照计Máy đo tia cực tím', 82);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '83', '自动读数显微镜Kính hiển vi đọc tự động', 83);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '84', '数显深度尺 Máy đo độ sâu kỹ thuật số', 84);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '85', '数显深度规 Máy đo độ sâu kỹ thuật số', 85);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '86', '外径千分尺（英制）Thiết bị đo đường kính ngoài', 86);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '87', '数字式木材测湿仪Máy kiểm tra độ ẩm gỗ kỹ thuật số', 87);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('chineseVietnamName', '9', '百分表Đồng hồ', 9);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('companyPosition', '0', 'A 车间（老厂后道）', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('companyPosition', '1', 'B 车间（老厂加工）', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('companyPosition', '2', 'L 车间（新厂毛坯库）', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('companyPosition', '3', 'M 车间（新厂装配）', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('companyPosition', '4', 'AB办公室（老厂）', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('companyPosition', '5', 'LM办公室（新厂）', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('companyPosition', '6', 'AB仓库（老厂机房）', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('companyPosition', '7', 'LM仓库（新厂机房）', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerName', '0', 'Màn hình 显示器', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerName', '1', 'Máy in   打印机', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerName', '2', 'Máy in mầu  彩色打印机', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerName', '3', 'Laptop  笔记本', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerName', '4', 'Máy cây 台式电脑', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerName', '5', 'Tivi  电视机', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerName', '6', 'Sever 服务器', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerName', '7', 'Loa 音响', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerName', '8', 'IPad 平板电脑', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerState', '0', 'Bình thường 正常', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerState', '1', 'Niêm phong 封存', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerState', '2', 'Sửa chữa 维修', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerState', '3', 'Tồn kho 库存', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('computerState', '4', 'Hỏng 报废', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('crashReason', '0', '操作不良Thao tác không tốt', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('crashReason', '1', '材料余量不符合图纸', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('crashReason', '2', '程序错误', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '0', 'CAM-OKC', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '1', 'APACHE', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '10', 'BOSS OILWELL', 10);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '11', 'WARREN VALVE', 11);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '12', 'FMC-HOUSTON', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '13', 'REXNORD', 13);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '14', 'PVD Drilling', 14);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '15', 'Douson Control Products', 15);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '16', 'KEENSS', 16);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '17', '计划外备库', 17);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '18', 'API审核库存', 18);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '19', 'FLOW American', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '2', 'CACTUS-USA', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '20', 'OMNI VALVE', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '21', 'MidCentral', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '3', 'Vault pressure control', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '4', 'STREAM-FLO USA', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '5', 'TechnipFMC', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '6', 'WOM', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '7', 'CANARY', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '8', 'INDEED', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('customerShortName', '9', 'CAM-MEXICO', 9);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('defectType', '1', 'Dimension 尺寸', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('defectType', '2', 'Hardness 硬度', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('defectType', '3', 'Thread 螺纹', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('defectType', '4', 'Appearance 外观', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('defectType', '5', 'True Position 位置度', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('defectType', '6', 'A&P 装配&试压', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('department', '0', '人事部 BP Nhân Sự ', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('department', '1', '生产部 BP Sản xuất ', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('department', '2', '质量部 BP Chất Lượng ', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('department', '3', '销售部 BP Kinh Doanh ', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('department', '5', '财务部 BP Kế toán ', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('department', '6', '采购部 BP Mua Hàng', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('department', '7', '供应商 Nhà cung cấp', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('deviceCheckLedgerState', '1', '有效Đạt tiêu chuẩn', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('deviceCheckLedgerState', '3', '过期Hết hạn', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('deviceCheckLedgerState', '4', '维修Sữa chữa', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('deviceCheckLedgerState', '5', '送检Gửi để kiểm tra', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('deviceCheckLedgerState', '6', '封存Niêm phong', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('deviceCheckLedgerState', '999', '报废Báo phế', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('equipmentPosition', '1', 'A 车间（老厂后道）', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('equipmentPosition', '2', 'B 车间（老厂加工）', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('equipmentPosition', '3', 'M车间（新厂装配）', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('equipmentPosition', '4', 'L车间（新厂库房）', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '1', '机器或工具的缺陷Khiếm khuyết của máy móc hoặc dụng cụ', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '10', '员工不能胜任此工作Năng lực của nhân viên không đáp ứng được công việc', 10);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '11', '工作程序中的任务是一项不安全的任务Nhiệm vụ trong quá trình làm việc là không an toàn', 11);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '12', '没有指明该项工作所需的正确的个人防护用品Nhân viên không được cấp phát đồ bảo hộ phù hợp với công việc', 12);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '13', '工作程序中已经指明正确的个人防护用品Các thiết bị bảo vệ cá nhân đúng cách đã được quy định trong quá trình làm việc', 13);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '14', '工作程序中已经指明正确的个人防护用品，但员工不知道其要求Nhân viên không biết rằng các thiết bị bảo hộ đúng đã được quy định trong quy trình làm việc ', 14);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '15', '员工没有正确的个人防护用品Nhân viên không có đồ bảo hộ phù hợp', 15);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '16', '员工有正确的个人防护用品，但没有正确使用Mặc dù được trang bị đồ bảo hộ nhưng nhân viên vẫn chưa sử dụng đúng cách', 16);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '17', '员工有正确的个人防护用品，但未能有效防止危害 Nhân viên có trang bị bảo hộ cá nhân phù hợp nhưng không ngăn chặn được mối nguy hiểm một cách hiệu quả', 17);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '18', '没有指明该工作所需要的紧急装置Không nêu rõ thiết bị khẩn cấp cần thiết cho công việc', 18);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '19', '已经指明该工作所需 要的紧急装置，但不能方便操作Thiết bị khẩn cấp cần thiết cho công việc đã được chỉ định, nhưng nó không dễ vận hành', 19);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '2', '没有检查机器导致未能发现危险的存在Không kiểm tra máy móc dẫn đến không phát hiện thấy nguy hiểm', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '20', '管理人员没有发现或预测潜在的危险状况Người quản lý không phát hiện hoặc dự đoán các tình huống nguy hiểm tiềm ẩn', 20);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '21', '主管没有发现或纠正违反工作程序的行为Người giám sát không phát hiện hoặc sửa lỗi vi phạm quy trình làm việc', 21);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '22', '没有明确主管对安全的责任、或主管不了解其安全责任Người giám sát không có hiểu rõ rang về trách nhiệm của mình', 22);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '3', '没有正确的使用机器或工具Không sử dụng máy móc hoặc thiết bị đúng cách ', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '4', '没有正确的机器或工具Không có máy móc hoặc thiết bị chính xác', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '5', '机器的设计导致员工紧张或导致员工出错Thiết kế của máy móc khiên nhân viên lo lắng dẫn đến mắc lỗi', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '6', '机器或工具的质量导致危险状况Chất lượng của máy móc hoặc công cụ gây ra tình huống nguy hiểm', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '7', '完成该任务工作场所不够大Nơi làm việc không đủ rộng để hoàn thành nhiệm vụ', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '8', '没有书面或书籍的工作程序Không có quy trình làm việc', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('eventReason', '9', '工作程序存在，但员工没有遵守Nhân viên không tuân theo quy trình làm việc', 9);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('improveReason', '1', '员工水平或安排问题(如安排新员工加工较为复杂产品)  Sắp xếp công việc không phù hợp với trình độ chuyên môn của người vận hành (sắp xếp hàng phức tạp cho người mới làm)', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('improveReason', '10', '刀具准备的异常(如刀长错误或是螺丝锁紧问题)Có sự cố bất thường trong quá trình chuẩn bị dao cụ ( đo chiều dài dao sai hoặc ốc vít không được vặn chặt)', 10);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('improveReason', '11', '运行错误的程序或错误地切断程序、重新运行程序 .Chạy sai trình hoặc cắt trình , chạy lại trình không đúng', 11);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('improveReason', '12', '技术交接不明确(技术班长与组员的交接)/技术交付不彻底 Đội kỹ thuật không giao tiếp đầy đủ , rõ ràng , chi tiết những điều cần chú ý khi gia công sản phẩm', 12);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('improveReason', '2', '机床故障(如中心水不出等)  Lỗi máy công cụ ( ví dụ nước xuyên tâm bị ngắt bất thường)', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('improveReason', '3', '毛坯余量过多 Phôi vật liệu để lượng dư quá nhiều', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('improveReason', '4', '程序错误或刀具路径不合理 Chương trình sai đường chạy dao không đúng xảy ra va chạm', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('improveReason', '5', '误操作或操作不当 Thao tác sai hoặc vận hành không đúng quy trình', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('improveReason', '6', '刀片/钻尖的异常磨损未及时更换  Chíp dao / mũi khoan bị mòn bất thường không phát hiện và thay thế kịp thời', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('improveReason', '7', '组员间交接不到位(如轮岗吃饭/休息间隙造成的刀具损坏) Giao tiếp trao đổi không đầy đủ (thời gian đi ăn hoặc giờ nghỉ giải lao không có sự giao tiếp đầy đủ về dao cụ ,sản phẩm đang chạy)', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('improveReason', '8', '工装不牢靠或不稳定等装夹问题造成的刀具损坏  Đồ gá không phù hợp hoặc không ổn định dẫn đến việc hỏng dao cụ trong quá trình gia công', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('improveReason', '9', '特殊工况下(如断续切削或特材加工等不稳定工况)造成的刀具损坏 Điều kiện gia công đặc biệt ví dụ như vật liệu  có độ cứng cao dẫn đến việc dao cụ mài mòn hoặc hỏng', 9);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('inventoryOutOfPlanType', '1', '毛坯 Phôi liệu', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('inventoryOutOfPlanType', '2', '小零件 Linh kiện', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('inventoryOutOfPlanType', '3', '成品 Thành phẩm', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('inventoryOutOfPlanType', '4', '半成品（动过刀）Bán thành phẩm', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('optimizeType', '0', 'EHS安全 An toàn EHS', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('optimizeType', '1', '效率 Hiệu suất', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('optimizeType', '2', '标准化 Tiêu chuẩn hóa', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('optimizeType', '3', '产品质量 Chất lượng sản phẩm', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('optimizeType', '4', '成本 Chi phí', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('optimizeType', '5', '产品工艺优化Tối ưu hóa quy trình sản phẩm', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('process', '1', 'Process inspection 过程', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('process', '2', 'Incoming inspection 进货', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('process', '3', 'Final inspection 终检', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('process', '4', 'A&P inspection 装配试压', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '1', 'OP10车床', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '10', 'OP50加工中心', 10);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '11', 'OP50车床', 11);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '12', 'OP60加工中心', 12);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '13', 'OP60车床', 13);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '14', 'OP70车床', 14);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '15', '其它（备注写内容）', 15);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '16', '外协转回加工', 16);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '17', 'JUFENG', 17);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '18', 'ANHDUNG', 18);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '19', 'TDM', 19);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '2', 'OP10加工中心', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '20', '外协成品', 20);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '3', 'OP20车床', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '4', 'OP20加工中心', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '5', 'OP30车床', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '6', 'OP30加工中心', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '7', 'OP40车床', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processProcedure', '8', 'OP40加工中心', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processType', '0', '半成品 Bán thành phẩm', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('processType', '1', '成品 Thành phẩm', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '1', '总经理 tổng giám đốc', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '10', '工艺工程师后道 kỹ sư công trình công nghệ B', 10);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '101', '合作伙伴', 101);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '11', '工艺员 nhân viên công nghệ', 11);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '12', 'CNC技术员兼班长Tổ trưởng NV kỹ thuật CNC', 12);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '13', '总计划 tổng kế hoạch', 13);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '14', '生产副经理 phó giám đốc sản xuất', 14);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '15', ' 计划员Nhân viên kế hoạch', 15);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '16', '电工工程师 & EHS专员Kỹ sư cơ điện & An toàn', 16);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '17', '生产主管 Chủ quản sản xuất', 17);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '18', '生产副主管Phó phòng sản xuất', 18);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '19', '数控组长Trưởng nhóm máy tiện', 19);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '2', '副总经理 phó tổng giám đốc', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '20', ' 数控操作员NV Vận hành máy tiện', 20);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '21', '加工中心组长Trưởng nhóm gia công trung tâm', 21);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '22', '加工中心操作员NV Vận hành Gia công trung tâm', 22);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '23', '生产后道主管 Trưởng phòng sản xuất', 23);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '24', '后道班长Tổ trưởng đóng hàng', 24);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '25', ' 叉车组长 tổ trưởng xe nâng ', 25);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '26', '叉车工  Nhân viên xe nâng', 26);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '27', ' 装配工Nhân viên lắp ráp', 27);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '28', ' 标识硬度组长Trưởng nhóm khắc dấu', 28);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '29', '标识员Nhân viên khắc dấu', 29);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '3', '工厂厂长兼生产&采购部经理 Giám đốc điều hành', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '30', '装箱员组长Trưởng nhóm đóng hàng', 30);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '31', '装箱员 Nhân viên đóng hàng', 31);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '32', '试压员Nhân viên thử áp', 32);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '33', '质量部经理兼销售技术Giám đốc Kinh doanh & KT chất lượng', 33);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '34', '销售经理 giám đốc chất lượng', 34);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '35', '商务进出口人员Chuyên viên Xuất nhập khẩu', 35);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '36', 'MTR员Nhân viên MTR', 36);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '37', '销售员  nhân viên kinh doanh', 37);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '38', '销售助理 trợ lý kinh doanh ', 38);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '39', ' QC主管 Trưởng phòng QC', 39);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '4', '生产经理  giám đốc sản xuất', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '40', '巡检班长 Tổ trưởng kiểm tra QC đầu vào', 40);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '41', ' 巡检员 Nhân viên kiểm tra QC đầu vào', 41);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '42', ' MT&终检班长 Tổ trưởng QC&MT', 42);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '43', ' MT检验员 Nhân viên kiểm nghiệm MT', 43);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '44', '终检员 Nhân viên OQC ( nhân viên QC đầu ra)', 44);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '45', '试压员（检查压力） Nhân viên đo áp suất ( kiểm tra áp suất )', 45);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '46', '检验员 Nhân viên QC', 46);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '47', '财务&人资行政经理 Giám đốc tài chính & HCNS', 47);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '48', '人事主管 Chủ quản  nhân sự ', 48);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '49', '会计长  Kế toán trưởng', 49);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '5', '采购主管chủ quản mua hàng', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '50', ' 会计综合 Kế toán tổng hợp ', 50);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '51', ' 仓库组长Trưởng nhóm Kho', 51);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '52', ' 仓库员 Nhân viên kho', 52);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '53', '人事招聘专员  Chuyên viên nhân sự tuyển dụng', 53);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '54', ' EHS专员 chuyên viên EHS ', 54);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '55', ' 清洁工 Tạp vụ ', 55);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '56', '终检&试压的组长Nhóm trưởng QC và Kiểm tra áp suất', 43);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '57', '装配组长 tổ trưởng lắp ráp', 26);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '58', '试压组长 tổ trưởng  thử áp', 31);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '6', '采购专员 Chuyên viên mua hàng', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '7', '生产工艺高级主管Trưởng phòng CN cấp cao', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '8', '新车间工艺主管Chủ quản công nghệ', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('profession', '9', '高级工艺工程师CNC  Kỹ sư công nghệ cấp cao CNC', 9);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityDealOpinion', '1', '① Reuse 回用', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityDealOpinion', '2', '② Rework 返工', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityDealOpinion', '3', '③  Reject 拒收', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityDealOpinion', '4', '④  Scrap 报废', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityDealOpinion', '5', '⑤ SDR', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityDealOpinion', '6', '⑥ 见备注', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '1', '人-不会、不懂、没经验 Con người: không biết, không hiểu, không có kinh nghiệm', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '10', '法-工艺未验证Phương pháp: quy trình chưa được xác minh', 10);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '11', '法-工艺已验证，但突发失效Phương pháp: quy trình đã được xác minh nhưng đột nhiên xảy ra sự cố', 11);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '12', '法-工艺紧急调整Phương pháp: Điều chỉnh quy trình khẩn cấp', 12);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '13', '环-未预测环境变化Môi trường: không thể dự đoán được những thay đổi của môi trường', 13);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '14', '环-预测环境变化，但无预案Môi trường: Dự đoán trước những thay đổi của môi trường nhưng chưa có kế hoạch ứng phó', 14);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '15', '测-检具不匹配Đo lường: Công cụ  kiểm tra không phù hợp', 15);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '16', '测-检具匹配，但不稳定Đo lường: Công cụ kiểm tra phù hợp nhưng không ổn định', 16);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '17', '测-检具突发失效Đo lường: Sự cố đột ngột của các công cụ kiểm tra', 17);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '18', '其他Những nguyên nhân khác', 18);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '2', '人-没有收到指令Con người: không nhận được sự hướng dẫn', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '3', '人-收到指令但不执行Con người:  nhận được sự hướng dẫn nhưng không tiến hành theo', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '4', '机-设备不匹配Máy móc: Thiết bị không phù hợp', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '5', '机-设备匹配，但不稳定Máy móc: Thiết bị phù hợp nhưng không ổn định', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '6', '机-设备突发故障Máy móc: Thiết bị bị hỏng hóc đột ngột', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '7', '料-图纸不合理Phôi liệu: Không phù hợp với bản vẽ', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '8', '料-切削余量不合适Phôi liệu: Phoi không được loại bỏ một cách phù hợp', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('qualityReason', '9', '料-残余应力Phôi liệu: Ứng suất dư', 9);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('repairType', '1', '内修', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('repairType', '2', '外修', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('responsibleTeam', '0', '生产技术 Công nghệ sản xuất', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('responsibleTeam', '1', 'CNC A 战 Nhóm CNC A.', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('responsibleTeam', '2', 'CNC B 越 Nhóm CNC B', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('responsibleTeam', '3', '标识和检验 Nhận dạng và kiểm tra', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('responsibleTeam', '4', '新车间班组 Đội ngũ hội thảo mới', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('responsibleTeam', '5', '办公室 văn phòng', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('responsibleTeam', '6', '安全设备 Thiết bị an toàn', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('responsibleTeam', '7', '生产管理 Quản lý sản xuất', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('schedule', '0', '白班 Ca ngày6:00~15:00', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('schedule', '1', '中班 Ca hai14:00~23:00', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('schedule', '2', '夜班 Ca đêm22:00~7:00', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('schedule', '3', '白班 Ca ngày 12H', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('schedule', '4', '夜班 Ca đêm 12H', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('skillDealOpinion', '1', '①  Reuse 回用', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('skillDealOpinion', '2', '② Rework 返工', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('skillDealOpinion', '3', '③ Reject 拒收', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('skillDealOpinion', '4', '④ Scrap 报废', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('skillDealOpinion', '5', '⑤ SDR', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('skillDealOpinion', '6', '⑥ 见备注', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent1', '0', '装夹工件 超20分钟 Gá đặt phôi ', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent1', '1', '砂光洁度、去毛刺 超5分钟 Đánh bóng độ nhám, mài bavia, quá 5 phút', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent1', '10', '5S 保养 超5分钟  Duy trì việc vệ sinh 5S', 10);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent1', '2', '测量（包含首检） Đo超5分钟', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent1', '3', '待操作（设备无人操作，请假超30分钟） Chờ người Thao tác', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent1', '4', '设备维修 超5分钟 Sữa chữa hỏng hóc・đối ứng vấn đề ', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent1', '5', '换夹具 超5分钟 Thay đồ gá ', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent1', '6', '暂停 （等校准卡尺，等量具）超5分钟 Chờ( chờ hiệu chuẩn thước, …)', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent1', '7', '清洁工作台 超5分钟 Vệ sinh bàn máy ', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent1', '8', '等行车 超5分钟  Đợi cần cẩu ', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent1', '9', '设备检查加油 超5分钟（日检查-月检查）Kiểm tra (hàng ngày・hàng tháng) ', 9);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent2', '0', '装夹工件 超20分钟 Gá đặt phôi ', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent2', '1', '砂光洁度、去毛刺 超5分钟 Đánh bóng độ nhám, mài bavia, quá 5 phút', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent2', '10', '5S 保养 超5分钟  Duy trì việc vệ sinh 5S', 10);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent2', '2', '测量（包含首检） Đo超5分钟', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent2', '3', '待操作（设备无人操作，请假超30分钟） Chờ người Thao tác', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent2', '4', '设备维修 超5分钟 Sữa chữa hỏng hóc・đối ứng vấn đề ', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent2', '5', '换夹具 超5分钟 Thay đồ gá ', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent2', '6', '暂停 （等校准卡尺，等量具）超5分钟 Chờ( chờ hiệu chuẩn thước, …)', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent2', '7', '清洁工作台 超5分钟 Vệ sinh bàn máy ', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent2', '8', '等行车 超5分钟  Đợi cần cẩu ', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent2', '9', '设备检查加油 超5分钟（日检查-月检查）Kiểm tra (hàng ngày・hàng tháng) ', 9);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent3', '0', '装夹工件 超20分钟 Gá đặt phôi ', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent3', '1', '砂光洁度、去毛刺 超5分钟 Đánh bóng độ nhám, mài bavia, quá 5 phút', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent3', '10', '5S 保养 超5分钟  Duy trì việc vệ sinh 5S', 10);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent3', '2', '测量（包含首检） Đo超5分钟', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent3', '3', '待操作（设备无人操作，请假超30分钟） Chờ người Thao tác', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent3', '4', '设备维修 超5分钟 sữa chữa hỏng hóc・đối ứng vấn đề ', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent3', '5', '换夹具 超5分钟 Thay đồ gá ', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent3', '6', '暂停 （等校准卡尺，等量具）超5分钟 Chờ( chờ hiệu chuẩn thước, …)', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent3', '7', '清洁工作台 超5分钟 Vệ sinh bàn máy ', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent3', '8', '等行车 超5分钟  Đợi cần cẩu ', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('stopWorkingContent3', '9', '设备检查加油 超5分钟（日检查-月检查）Kiểm tra (hàng ngày・hàng tháng) ', 9);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('storage', '1', '仓库 Kho', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('storage', '2', '生产现场Sản xuất', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('storage', '3', '计量室，Phòng đo', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('userProperty', '1', '车间 Xưởng SX', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('userProperty', '2', '科室 Văn phòng', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('vocationType', '1', 'Việc riêng 事假', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('vocationType', '10', '探亲假Nghỉ thăm thân', 10);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('vocationType', '2', 'Nghỉ phép năm 年假', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('vocationType', '3', 'Nghỉ ốm BHXH 病假', 3);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('vocationType', '4', 'Nghỉ thai sản 产假', 4);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('vocationType', '5', 'Nghỉ tự do 旷工', 5);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('vocationType', '6', 'Không tham gia Team building  团建', 6);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('vocationType', '7', 'Nghỉ ma chay hiếu hỷ 婚假和丧假', 7);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('vocationType', '8', 'Không tham gia họp  会议', 8);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('vocationType', '9', 'Đi muộn/ về sớm 上下班迟到早退', 9);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('workMinute', '435', '8小时', 0);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('workMinute', '585', '12小时', 1);
UPDATE douson.MP_FORUM SET CATEGORY = 'dousonVoiceCommunity' WHERE CATEGORY IS NULL;
UPDATE douson.MP_FORUM SET COMMENTARY_SHOW_TYPE = 0 WHERE COMMENTARY_SHOW_TYPE IS NULL;
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('nationality', '1', 'Vietnam', 1);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('nationality', '2', 'China', 2);
INSERT INTO douson.MP_INDUSTRY_PARAM (PARAM_CATEGORY_ID, PARAM_CODE, PARAM_NAME, SORTER) VALUES ('userProperty', '3', '外部人员 cá nhân ngoài công ty', 3);
