alter table dmmp.MP_USER ADD `ORGANIZATIONAL_STRUCTURE` VARCHAR(1024) comment '组织架构';
update dmmp.MP_USER SET ORGANIZATIONAL_STRUCTURE = CONCAT(',', DEPARTMENT, ',') WHERE ORGANIZATIONAL_STRUCTURE IS NULL;
